[package]
name = "cliw_clap_demo"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.29", features = [
    "derive",
] }

cliw = { version = "0.1.1" , features = [
    "alert",
    "urlargs",
] }
